apiVersion:${BUILD_NUMBER}
kind:${BUILD_NUMBER}
metadata:${BUILD_NUMBER}
  name:${BUILD_NUMBER}
  namespaces:${BUILD_NUMBER}
spec:${BUILD_NUMBER}
  selector:${BUILD_NUMBER}
    matchLabels:${BUILD_NUMBER}
      app:${BUILD_NUMBER}
  replicas:${BUILD_NUMBER}
  template:${BUILD_NUMBER}
    metadata:${BUILD_NUMBER}
      labels:${BUILD_NUMBER}
        app:${BUILD_NUMBER}
    spec:${BUILD_NUMBER}
      containers:${BUILD_NUMBER}
      - name:${BUILD_NUMBER}
        image:${BUILD_NUMBER}
        ports:${BUILD_NUMBER}
        - containerPort:${BUILD_NUMBER}
