apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example
  namespace: testing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example
  type: NodePort