apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  # namespaces: testing
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sample-app
    spec: 
      containers:
      - name: sample-app
        image: tarmizy/test
        ports:
        - containerPort: 80
