apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  # namespaces: testing
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app
    spec: 
      containers:
      - name: demo-app
        image: tarmizy/test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
